# Gradle Properties
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Project Details
project_jvm_version=25

project_group=com.viaversion
project_name=ViaNeoForgePlus
project_version=4.6.2-neoforge.1
project_description=Minecraft NeoForge mod that allows you to join EVERY Minecraft server version (Classic, Alpha, Beta, Release, April Fools, Bedrock)

publishing_dev_id=florianreuth
publishing_dev_name=Florian Reuth
publishing_dev_mail=git@florianreuth.de

minecraft_version=26.2
neoforge_version=26.2.0.11-beta

# Allows running of `gradle test` - disable after running
updating_minecraft=false

# Set to empty to use the Minecraft version above, otherwise use version ranges: >=1.21.7 <=1.21.8
supported_minecraft_versions=
