modLoader="javafml"
loaderVersion="[11,)"
license="GPL-3.0-only"

[[mods]]
modId="vianeoforgeplus"
version="${version}"
displayName="ViaNeoForgePlus"
logoFile="assets/viafabricplus/icon.png"
authors="Florian Reuth (EnZaXD), RK_01, ViaVersion contributors"
description='''${description}'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.vianeoforgeplus]]
modId="neoforge"
type="required"
versionRange="[${neoForgeVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.vianeoforgeplus]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="viafabricplus.mixins.json"

[[mixins]]
config="viafabricplus-visuals.mixins.json"

[features.vianeoforgeplus]
javaVersion="[25,)"
