blank_issues_enabled: false
contact_links:
  - name: Dev builds
    url: https://github.com/fadeway37/ViaNeoForgePlus/actions
    about: Before reporting a bug, please check if the latest successful CI build fixes your issue.
  - name: ViaVersion Discord
    url: https://discord.gg/viaversion
    about: For smaller issues or questions, you can also join our Discord server.
