name: Feature Request
description: Suggest a feature for ViaNeoForgePlus
labels: [ S-needs-triage, T-feature ]

body:
  - type: markdown
    attributes:
      value: |
        **Before requesting a new feature, please check whether the latest build from https://github.com/fadeway37/ViaNeoForgePlus/actions already includes a solution.**

        You can upload screenshots or videos in any text field when relevant.

  - type: textarea
    attributes:
      label: Problem Description
      description: |
        Describe the problem you are facing or explain why this feature would be useful.
      placeholder: |
        I am always frustrated by...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: |
        Describe the solution or feature you would like to see implemented.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: |
        Describe any alternative solutions or workarounds you have considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Does this feature apply to a specific Minecraft version, mod loader, or environment?
    validations:
      required: false
